// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZn_itHXBIrh8D2I57JtxZGzPqcxfuUrc',
    appId: '1:184136420085:web:7e0d474ba681758e8093bc',
    messagingSenderId: '184136420085',
    projectId: 'hris-modern',
    authDomain: 'hris-modern.firebaseapp.com',
    storageBucket: 'hris-modern.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PDpTgM4l2bPTK4qOdyQYfTM1A6Io5RQ',
    appId: '1:184136420085:android:d352c021094402bd8093bc',
    messagingSenderId: '184136420085',
    projectId: 'hris-modern',
    storageBucket: 'hris-modern.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12tBzjZKV2xchcoCQaFS327q7kQhs9tg',
    appId: '1:184136420085:ios:c2c3d60bf6ded86c8093bc',
    messagingSenderId: '184136420085',
    projectId: 'hris-modern',
    storageBucket: 'hris-modern.firebasestorage.app',
    iosBundleId: 'com.example.hrisAbsensiModern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12tBzjZKV2xchcoCQaFS327q7kQhs9tg',
    appId: '1:184136420085:ios:c2c3d60bf6ded86c8093bc',
    messagingSenderId: '184136420085',
    projectId: 'hris-modern',
    storageBucket: 'hris-modern.firebasestorage.app',
    iosBundleId: 'com.example.hrisAbsensiModern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZn_itHXBIrh8D2I57JtxZGzPqcxfuUrc',
    appId: '1:184136420085:web:3f1031d305d18a318093bc',
    messagingSenderId: '184136420085',
    projectId: 'hris-modern',
    authDomain: 'hris-modern.firebaseapp.com',
    storageBucket: 'hris-modern.firebasestorage.app',
  );
}
